settings:
  keyb_path: /home/haseeb/.config/keyb/keyb.yml
  debug: false
  reverse: false
  mouse: true
  search_mode: false
  sort_keys: false
  title: ""
  prompt: 'keys > '
  prompt_location: top
  placeholder: '...'
  prefix_sep: ;
  sep_width: 4
  margin: 0
  padding: 1
  border: hidden
color:
  prompt: ""
  cursor_fg: ""
  cursor_bg: ""
  filter_fg: '#FFA066'
  filter_bg: ""
  counter_fg: ""
  counter_bg: ""
  placeholder_fg: ""
  placeholder_bg: ""
  border_color: ""
keys:
  quit: q, ctrl+c
  up: k, up
  down: j, down
  half_up: ctrl+u
  half_down: ctrl+d
  full_up: ctrl+b
  full_bottom: ctrl+f
  first_line: g
  last_line: G
  top: H
  middle: M
  bottom: L
  search: /
  clear_search: alt+d
  normal: esc
