- create:
    - ~/.config/fish
    - ~/.config/fish/functions
    - ~/.config/fish/completions
    - ~/.config/fish/conf.d

- link:
    ~/.config/fish:
      path: fish/**
      glob: true
      force: true

- shell:
    - command: curl -fsSL https://starship.rs/install.sh | sh -s -- --yes
      stdout: true
      stderr: true
