- tap:
    - homebrew/cask-fonts

- brew:
    - zoxide
    - bat
    - fd
    - ripgrep
    - exa
    - httpie
    - hyperfine
    - dust
    - tealdeer
    - sd
    - diff-so-fancy
    - ctop
    - broot
    - procs
    - neofetch
    - yq
    - fzf
    - nvim
    - vim
    - make
    - entr
    - starship
    - fish
    - go
    - font-hack-nerd-font
    - ag
    - mcfly
    - choose
    - cheat
    - gping
    - procs
    - curlie
    - dog
    - thefuck
    - chafa
    - navi
    - go-task
    - lazygit
    - bottom
    - tree-sitter
    - tmux
    - coreutils

- shell:
    - tldr --update
