- yay:
    - zoxide
    - bat
    - fd
    - ripgrep
    - exa
    - httpie
    - hyperfine
    - dust
    - tealdeer
    - sd
    - diff-so-fancy
    - ctop
    - broot
    - procs
    - neofetch
    - btop
    - jq
    - fzf
    - vim
    - make
    - flameshot
    - entr
    - ttf-fira-code
    - zsh

- shell:
    - tldr --update
