- tap:
    - homebrew/cask-fonts

- brew:
    - ag
    - amethyst
    - bat
    - bottom
    - broot
    - chafa
    - cheat
    - choose
    - coreutils
    - ctop
    - curlie
    - diff-so-fancy
    - dog
    - dust
    - entr
    - exa
    - fd
    - fish
    - font-hack-nerd-font
    - fzf
    - go
    - go-task
    - gping
    - httpie
    - hyperfine
    - lazydocker
    - lazygit
    - make
    - mcfly
    - mdp
    - navi
    - neofetch
    - nvim
    - procs
    - ripgrep
    - sd
    - starship
    - tealdeer
    - thefuck
    - tmux
    - tree-sitter
    - yq
    - zoxide
- shell:
    - tldr --update
