- shell:
    - echo "deb http://deb.debian.org/debian bullseye-backports main" | sudo tee /etc/apt/sources.list.d/backports.list
    - curl -sS https://starship.rs/install.sh | sh -s -- --yes

- apt:
    - zsh
    - jq
    - fzf
    - vim
    - make
    - fish/bullseye-backports