- yay:
    - zoxide
    - bat
    - fd
    - ripgrep
    - exa
    - httpie
    - hyperfine
    - dust
    - tealdeer
    - sd
    - diff-so-fancy
    - ctop
    - broot
    - procs
    - neofetch
    - btop
    - yq
    - fzf
    - nvim
    - vim
    - make
    - entr
    - ttf-fira-code
    - solaar
    - psensor
    - starship
    - fish
    - duf
    - ag
    - mcfly
    - choose
    - cheat
    - gping
    - procs
    - curlie
    - dog
    - wl-clipboard
    - fuck
    - chafa
    - navi
    - go-task
    - lazygit
    - bottom
    - gdu
    - tree-sitter-cli
    - tmux
    - lazydocker
    - mdp

- shell:
    - tldr --update
