- yay:
    - ag
    - asciiramia
    - bottom
    - broot
    - cowsay
    - chafa
    - cheat
    - choose
    - cmatrix
    - ctop
    - curlie
    - git-delta
    - diff-so-fancy
    - dog
    - duf
    - dust
    - entr
    - exa
    - fd
    - fish
    - fortune-mod
    - fuck
    - fzf
    - gdu
    - go-task
    - go-yq
    - gping
    - httpie
    - hyperfine
    - lazydocker-bin
    - lazygit
    - make
    - mcfly
    - mdp
    - navi
    - neofetch
    - neovim
    - procs
    - procs
    - psensor
    - ripgrep
    - sd
    - sl
    - solaar
    - starship
    - tealdeer
    - tmux
    - tree-sitter
    - wl-clipboard
    - zoxide
- shell: [tldr --update]
