- create:
    - ~/.config/qtile
    - ~/.config/dunst
    - ~/.config/rofi

- link:
    ~/.config/qtile/:
      path: tiling/qtile/**
      glob: true
      create: true

    ~/.config/picom.conf: tiling/picom.conf
    ~/.config/dunst/dunstrc: tiling/dunstrc
    ~/.config/rofi/:
      path: tiling/rofi/**
      glob: true
      create: true
      force: true
    # /etc/lightdm/lightdm.conf: tiling/lightdm/lightdm.conf
    # /etc/lightdm/lightdm-webkit2-greeter.conf: tiling/lightdm/lightdm-webkit2-greeter.conf
# - yay:
#      - qtile
#      - qtile-extras-git
#     - lightdm
#     - web-greeter
#     - lightdm-webkit-theme-aether
#     - rofi
#     - picom
#     - dunst

# - shell:
#     - git clone --depth=1 https://github.com/adi1090x/rofi.git
#     - cd rofi
#     - chmod +x setup.sh
#     - ./setup.sh
