- ifanylinux:
    - link:
        ~/.config/alacritty/alacritty.yml:
          path: alacritty/linux/alacritty.yml
          force: true

- ifmacos:
    - link:
        ~/.config/alacritty/alacritty.yml:
          path: alacritty/macos/alacritty.yml
          force: true
