- link:
    # Linux specific config
    ~/.config/Code/User/settings:
      path: vscode/settings.json
      force: true

    ~/.config/Code/User/keybindings.json:
      path: vscode/linux/keybindings.json
      force: true

    # MacOS specific config
    ~/Library/Application Support/Code/User/keybindings.json:
      if: "[[ `uname` = Darwin ]]"
      path: vscode/macos/keybindings.json
      force: true

    ~/Library/Application Support/Code/User/settings.json:
      if: "[[ `uname` = Darwin ]]"
      path: vscode/settings.json
      force: true
