- link:
    "/mnt/c/Users/Haseeb Majid/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json":
      if: "[ `grep 'WSL' /proc/version` ]"
      path: windows_terminal/settings.json
