# fly.toml app configuration file generated for majiy00-shell on 2023-07-29T14:31:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "majiy00-shell"
primary_region = "lhr"

[build]
  image = "ghcr.io/ellie/atuin:main"

[env]
  ATUIN_HOST="0.0.0.0"
  ATUIN_PORT=8888
  ATUIN_OPEN_REGISTRATION=false

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[experimental]
  cmd = ["server", "start"]
