keys:
  - &users:
    - &haseeb F04F743A24CD81B628A20667CD20E7373D83B71C
  - &hosts:
    - &framework age1kzxen8ynw28h935jnjc9t8cx4p8mv6angk5suvkp6ntu4am9pe4smfw22z

creation_rules:
  - path_regex: hosts/framework/secrets.ya?ml$
    key_groups:
    - age:
      - *framework
      pgp:
      - *haseeb

  - path_regex: nixos/secrets.ya?ml$
    key_groups:
    - age:
      - *framework
      pgp:
      - *haseeb

  - path_regex: home-manager/secrets.ya?ml$
    key_groups:
    - age:
      - *framework
      pgp:
      - *haseeb

