- clean: [ "~" ]

- create:
      - ~/.config

- defaults:
      link:
          relink: true
          create: true
          force: true

# - shell:
#     - [git submodule update --init --recursive, Installing submodules]
