- name: neovim
  keybinds:
    - name: Replace everything between quotes with what is yanked
      key: vi""+p`
    - name: Copy entire function (golang or c style)
      key: va{Vy
    - name: Delete without overwriting default register
      key: _dd

- name: telescope undo
  keybinds:
    - name: Copy additions
      key: ctrl + r
    - name: Copy deletions
      key: shift + ctrl + r
    - name: Restore this version
      key: ctrl + c + r

- name: vim surround
  keybinds:
    - name: Delete surrounding function
      key: d + s + f
    - name: Surround word in parenthesis
      key: g + z + a + i + w + )

- name: firefox
  keybinds:
    - name: Attach tab
      key: ctrl + shift + v
    - name: Detach tab
      key: ctrl + shift + space

- name: fish/fzf
  keybinds:
    - name: Search Directory
      key: ctrl + alt + f
    - name: Search git log
      key: ctrl + alt + l
    - name: Search search process
      key: ctrl + alt + p

