theme:
  lightTheme: false
  activeBorderColor:
    - "#a6d189" # Green
    - bold
  inactiveBorderColor:
    - "#c6d0f5" # Text
  optionsTextColor:
    - "#8caaee" # Blue
  selectedLineBgColor:
    - "#414559" # Surface0
  selectedRangeBgColor:
    - "#414559" # Surface0
  cherryPickedCommitBgColor:
    - "#81c8be" # Teal
  cherryPickedCommitFgColor:
    - "#8caaee" # Blue
  unstagedChangesColor:
    - red # Red
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

customCommands:
  - key: "W"
    prompts:
      - type: "input"
        title: "Commit"
        initialValue: ""
    command: git commit -m "{{index .PromptResponses 0}}" --no-verify
    context: "global"
    subprocess: true
